### ISSUE TITLE
Desenhar um design para o site portifólio

### ISSUE THREAD

**Issue by frattezi** [fmagesty/primeiro-ciclo-de-mentoria#1]
Pode ser em um papel, figma, draw.io você escolhe

Desenhe um modelo para o seu site, descreva abstratamente, os componentes utilizados para montar cada tela. A partir deste design vamos criar tarefas de desenvolvimento

**Comment by frattezi** [comment]
Exemplo: https://www.figma.com/file/nkn42MkcuM4OC7IRArHWvH/PokeBox?node-id=0%3A1

**Comment by frattezi** [comment]
Adicionar também um sketch para aplicação de star wars

**Comment by fmagesty** [comment]
AE https://www.figma.com/file/1BcRKmWLFXgL8r0rtJ1bUW/Untitled?node-id=0%3A1

**Comment by fmagesty** [comment]
movi pro review em progress. se tiver fazendo algo errado me fala

**Comment by fmagesty** [comment]
VERSAO 2: https://app.diagrams.net/#G1UX_knhQlG0Jb6_Czza4-Try4OVqr942l
