### ISSUE TITLE
Create new repository for base projects

### ISSUE THREAD

**Issue by frattezi** [fmagesty/primeiro-ciclo-de-mentoria#12]
THe objective is to create a new repo to host our base projects.

 
This repo main branch will only hold the README for documentation, each base project should have it's own branch.
For this task to be done:

-  Create a new repo
- Give permission to @frattezi 
- Create a new branch called react-javascript.

**Comment by frattezi** [comment]
What the readme should have:

- Brief description of the repo project.
- Define a branch naming system
- List linking the base projects

**Comment by fmagesty** [comment]
done

**Comment by frattezi** [comment]
links
