### ISSUE TITLE
Starting our base react project

### ISSUE THREAD

**Issue by frattezi** [fmagesty/primeiro-ciclo-de-mentoria#13]
For this project we should follow this minimal approach for folder organization:

```bash
src/
|
| --- components/
      |
      | --- core/ # commom components
      | --- GeneralComponents.js ...
| --- assets/
     | --- img.png
| --- pages/
     |
     | --- MyPage.js
```

For each folder just start a simple react file.

**Comment by fmagesty** [comment]
https://github.com/fmagesty/base-projects

**Comment by frattezi** [comment]
The directory organization is not complete

**Comment by fmagesty** [comment]
https://github.com/fmagesty/base-projects/tree/react-javascript

I even created a tests folder to contain all the tests
