### ISSUE TITLE
Setup lint for the application

### ISSUE THREAD

**Issue by frattezi** [fmagesty/primeiro-ciclo-de-mentoria#15]
Estudar e aprender a configurar o linter de um projeto. Para este caso, use o **ESLINT** e **Prettier** com o padrão AirBnB.

Para aceite:

- Setup funcional do eslint no projeto existente.
- Configurar Eslint para utilizar o airbnb-styleguide
- Adicionar ao package.json um comando para lintar o código.
- Configuração do Vscode

Referências:
 - https://github.com/airbnb/javascript
 - https://eslint.org/
 - https://www.andrewmin.info/blog/react-setup/

**Comment by fmagesty** [comment]
I hope it is right now. I've made the changes to add linter and prettier and configured the JSON accordingly 

https://github.com/fmagesty/base-projects/tree/react-javascript

**Comment by frattezi** [comment]
NOw it's perfect!
