### ISSUE TITLE
Simplify App main script logic

### ISSUE THREAD

**Issue by frattezi** [fmagesty/primeiro-ciclo-de-mentoria#16]
Ok so first:

- Remove all text from your App.js file, let's create a new file somewhere else with the definition of for each projectCard description.
- Encapsulate the link logic in the `ProjectDescription` component.
- Add to your configuration object also the title and image references
- For each configuration in your config, render a new project card.

Example
```javascript
// in file data.js
const projectCard = [{title: "bla", image: "bla", description: "bla" }, {}, {}]
```

**Comment by fmagesty** [comment]
I've made all the map on the component ProjectCards and deleted ProjectDescription.
The component render dynamically now.

https://github.com/fmagesty/fmagesty/blob/main/src/Components/ProjectCard.js

**Comment by frattezi** [comment]
Perfect! But let's remove the `data` const to a different file?

It can be a `data.js` file you can organize it where you think it's better.

**Comment by frattezi** [comment]
The writing for the component it's not as expected in react syntax, it's wrong? Nope, but it's not usual.

Can you re-write your `const mapData` inside the component return? How do you do that?

**Comment by fmagesty** [comment]
done!
https://github.com/fmagesty/fmagesty/blob/main/src/Components/ProjectCard.js
https://github.com/fmagesty/fmagesty/blob/main/src/data.js

**Comment by frattezi** [comment]
now we're talking!
