### ISSUE TITLE
Setup Projects e exercises

### ISSUE THREAD

**Issue by frattezi** [fmagesty/primeiro-ciclo-de-mentoria#3]
Organizar no computador pessoal ambos os repositórios (via fork)
https://github.com/podcodar

**Comment by frattezi** [comment]
Objetivos:

- Estudar oque é um Fork https://docs.github.com/en/github/getting-started-with-github/fork-a-repo
- Garantir que os FORKS do projeto estão clonados e syncados no computador local.

**Comment by fmagesty** [comment]
> Organizar no computador pessoal ambos os repositórios (via fork)
> https://github.com/podcodar

ambos quais?

**Comment by fmagesty** [comment]
tem 18 repos la

**Comment by fmagesty** [comment]
c me falou pessoalmete mas nao lembro quais eram os 2. exercices e +1?

**Comment by fmagesty** [comment]
> Objetivos:
> 
> * Estudar oque é um Fork https://docs.github.com/en/github/getting-started-with-github/fork-a-repo
> * Garantir que os FORKS do projeto estão clonados e syncados no computador local.

done
